Added sample actor written in Go
leapp-to/snactor pull request #67
Opened 2017-11-20 20:58 UTC by artmello

- Added actor definition files
- Added actor source code written in Go
- Added Makefile for actor building
- Added support for "build-cmd" into actor definition

2017-11-20 21:03 UTC, artmello commented
@vinzenz / @shaded-enmity on Friday I spent sometime written a sample actor written in Go. I tried to use the approach that was discussed during last Cabal meeting. There is some questions that I don't know if I took the right approach (i.e. building actor before execution or adding a "build" method to snactor to be called by runner; passing building command via actor definition or always use "make" to build actor), but i am pushing this PR to share that.

2017-11-20 21:05 UTC, vinzenz requested changes
Please do not add the build step into the library - This should be done separately - e.g. during RPM build time  when - Or you have to do it manually or at least kick it off manually in the repo

2017-11-20 21:06 UTC, vinzenz commented on examples/actors/goactor/Makefile
> +all: | $(BASE) ; $(info $(M) building executable…)
please add a build target for this

2017-11-20 21:06 UTC, vinzenz commented on examples/actors/goactor/_actor.yaml
> +  build-cmd: make all
please do not specify this here

2017-11-20 21:06 UTC, vinzenz commented on snactor/definition.py
> +            self.build_cmd = execute.get('build-cmd')
ofc this has to be gone too

2017-11-20 21:07 UTC, vinzenz commented on snactor/executors/default.py
> +
and this section as well

2017-11-21 13:52 UTC, artmello commented
After discussion under Cabal meeting it was clear that snactor should not be responsible for building the actor and changes to YAML file would be unnecessary. So, I will close this PR

2017-11-21 13:52 UTC, closed without merging